### ISSUE TITLE
`countryCode` should be tested as a lower case string

### ISSUE THREAD

**Issue by robiseb** [pabio/redirect-russia#2]
## Description
`countryCode` string variable should be tested as a lower case string due to 
```ts
countryCode = json.country.toLowerCase();
```
[`v1.ts`, L.129](https://github.com/pabio/redirect-russia/blob/4865ce89db01be6ae7938bf97a866647c94599b7/v1.ts#L129)
## Relevant Context
In IP geolocation request code section.
```ts
if (countryCode === "RU") return redirect();
```
[`v1.ts`, L.134](https://github.com/pabio/redirect-russia/blob/4865ce89db01be6ae7938bf97a866647c94599b7/v1.ts#L134)
## Solution
Change `"RU"` by `"ru"` like
```ts
if (countryCode === "ru") return redirect();
```

**Comment by AnandChowdhary** [comment]
Thanks so much, all fixed!
