### ISSUE TITLE
Script is causing infinite redirect loop

### ISSUE THREAD

**Issue by Frazi1** [pabio/redirect-russia#5]
I'm from Russia, and I wanted to see how the script is working. I tried visiting https://redirectrussia.org/?from=redirectrussia.org and the only thing I see is my browser infinitely redirecting me somewhere and page being refreshed constantly. I can't really see what's on the page.

P.S. I dislike what's Russia is doing in Ukraine, but I also do not understand why regular russian people have to suffer on the internet because of it. I also do not like this script, but if you're publishing it, at least make it "usable" and make sure it provides useful information.

https://user-images.githubusercontent.com/14334350/156935162-28ace2a0-22f4-43bc-a625-bd0b65109760.mov

**Comment by AnandChowdhary** [comment]
Oops, all fixed! Happy to discuss the rationale behind the plugin in #3. :)
